### PR TITLE
Fifth milestone

### PR DESCRIPTION
**Pull request by bren2102**
Kindly request a code review for the fourth milestone of this calculator project.

1. App Component updated
2. ButtonPanel updated
3. Button updated

### CODE REVIEW

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello team  🌟

**Nice work on this project, but the following changes need to be done before moving on ⬇️** 

### ButtonPanel
* [ ] it implements `handleClick` function ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone5/panel/implementHandleClick.png)).
* [ ] it passes `handleClick` as `clickHandler` props to each `Button` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone5/panel/passToButton.png))
**- [OPTIONAL]** You could render the buttons using a loop.

* [ ] Linters config: Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by bren2102** [comment]
Thanks for the review

- The handleclick function has been added and it passes handleClick as clickHandler props to each Button.

- Also, no changes were made to the linters configuration, the file remains the same since it was created

**Review by Forison — CHANGES_REQUESTED** [review]
## Status:: Change Required🔴
# 🙋‍♂️ Brenda 
#### Good job on addressing the issues raised in the previous review, however, there are a few improvements we have to make for the application to be user friendly🤗 .
* [x] Currently the app throws an error when I divide any number by zero, Kindly make it return undefined.
* [x] Let us make the operation visible after we select one. When I enter an operation it does not display on the screen.
* [x] The ```%``` functionality is not well implemented, it is supposed to return the percentage of the number that precedes it selection.
* [x]  Computation like ```-6+3``` throws the application in error, kindly address it. It would be easier if the operation is displayed as the numbers do.

**[OPTIONAL]**
I this it would be better to have the calculator at the center of the page.

### That is is kindly make these changes and submit another review request🤗 .
#### Happy coding👩‍💻
Addo Forison

**Comment by bren2102** [comment]
Thanks for the review

- Now returns "undefined" when you divide any number by zero
- The operation is now displayed on the screen, although according to the requirements the total or the next one should be shown.
image
- The % functionality now shows the result immediately, before it needed an equal button
- "+/-" operation works correctly
- Now, the calculator is in the middle of the page

**Review by bellom — APPROVED** [review]
## Hi @bren2102  :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_*

**Pull request merged**
